---
id: 'tests:sdk:acceptance'
short_description: 'Run acceptance tests'
help: ~
stage: build
version: 0.1.0
command: 'php %sdk_dir%/vendor/bin/codecept run acceptance'
type: local_cli
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
